GradExam/Models/Report.cs
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GradExam.Models
{
    public class Report {
        public string Name;
        public List<Tuple<Course, double>> Courses;
        public double ConcentrationAvg { set; get; }

        public Report(string name, List<Tuple<Course, double>> courses) {
            Name = name;
            Courses = courses;
        }

        public Report(List<Tuple<Course, double>> courses) {
            Courses = courses;
        }
    }
    

}

GradExam/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using GradExam.Models;
using GradExam.Services;
using Microsoft.AspNetCore.Authorization;
using System.IO;
using GradExam.Services.PdfProvider.DataModel;
using GradExam.Services.PdfProvider;

namespace GradExam.Controllers
{
    [Authorize(Roles = "Admin,Director")]
    public class ReportController : Controller
    {
        private static List<Report> reportData;
        private static string reportName = "";

        IGradeExamRepository context;
        IMigraDocService _migraDoc;

        public ReportController(IGradeExamRepository context, IMigraDocService migraDoc) 
        {
            this.context = context;
            this._migraDoc = migraDoc;
        }

        public IActionResult Index() 
        {
            ViewBag.Semesters = context.GetDistinctSemesters();
            return View();
        }

        public ActionResult GetAggregateData(string time, int aggregate) {
            string agg = "";
            switch (aggregate) {
                case 1: agg = "Concentration";
                    break;
                case 2: agg = "Course";
                    break;
                case 3: agg = "Learning Outcome"; //return learning outcome
                    break;
                case 4: agg = "Question"; //return question
                    break;
            }
            reportName = agg;

            List<Report> data = context.ReadResponsesByAggregate(agg, time);
            reportData = data;
            return Json(data);
        }

        [HttpGet]
        public FileStreamResult PrintPDF()
        {
            var headers = new List<Tuple<string, int>>()
            {
                new Tuple<string, int>(reportName, 6),
                new Tuple<string, int>("Number of Students", 6),
                new Tuple<string, int>("Grade Average", 6)
            };

            var rows = new List<List<string>>();

            foreach (var n in reportData)
            {
                var column = new List<string>();

                if (n.Name != null)
                {
                    column.Add(n.Name.ToString());
                    int sum = 0;
                    foreach (var c in n.Courses)
                    {
                        sum += c.Item1.StudentCourses.Count();
                    }

                    column.Add(sum.ToString());

                    column.Add(n.ConcentrationAvg.ToString("0.##"));
                    rows.Add(column);
                }
                else
                {
                    foreach(var course in n.Courses)
                    {
                        column = new List<string>();
                        column.Add(course.Item1.Name);
                        column.Add(course.Item1.StudentCourses.Count().ToString());
                        column.Add(course.Item2.ToString("0.##"));
                        rows.Add(column);
                    }

                }

            }

            var data = new PdfData
            {
                DocumentTitle = "Report for " + reportName + "s",
                DocumentName = "AggregateReport",
                CreatedBy = User.Identity.Name ?? "Unknown",         // Ideally it'll be the user who is logged in
                ReportName = "Aggregate Report for " + reportName,
                Table = new PdfTable() { Headers = headers, RowData = rows },
                //ReportDescription = $"Amount of Courses: {courses.Count()}\nAmount of Concentrations: {courses.Select(m => m.Semester).Distinct().Count()}"
            };

            var path = _migraDoc.CreateMigraDocPdf(data);

            var stream = new FileStream(path, FileMode.Open);
            return File(stream, "application/pdf");
        }

    }
}

GradExam/Views/Report/Index.cshtml
@model IEnumerable<GradExam.Models.Course>
@{
    ViewData["Title"] = "Index";
}
<style>
    .container{
        max-width:100% !important;
    }
    
    .test {
        padding:0 !important;
    }

</style>
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>

<h2>Reports</h2>
<hr />
<div class="row">
    
    <div class="col-md-10">
        <select id="time" class="form-control eh">
            <option value="0">-- Select a Semester --</option>
            @foreach (var semester in ViewBag.Semesters) {
                <option value="@semester">@semester</option>
            }
        </select>
        <br />
        <select id = "aggregate"class="form-control" disabled>
            <option value="0">-- Select What to Aggregate --</option>
            <option value="1">Concentration</option>
            <option value="2">Course</option>
            <option value="3">Learning Outcome</option>
            <option value="4">Question</option>
        </select>
        <br />
        <div id="dataTable" class="hidden">
            <div class="col-sm-12" style="text-align: right;">
                @Html.ActionLink("Print PDF Report", "PrintPDF", "Report", null, new { target = "_blank", style = "color: blue;"})
            </div>
            @* Add Class hidden and an id and have it show on update *@
            <table class="display table table-bordered" id="data">
                <thead>
                    <tr>
                        <th></th>
                        <th id="label"></th>
                        <th>Number of Students</th>
                        <th>Grade Average</th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </div>
</div>

<script>
    var table = $('#data').DataTable();

    $('#time').on('change', function () {
        $('#aggregate').prop('disabled', false);
    });

    $('#data tbody').on('click', 'tr', function () {
        var child = table.row(this).child;
        if (child.isShown()) {
            child.hide();
        } else {
            child.show();
        }
        
    });


    $('#aggregate, #time').on('change', function () {
        var aggregate = $('#aggregate option:selected');
        var time = $('#time option:selected')
        $('#data').removeClass('hidden');
        $('#label').text(aggregate.text() + "s");
        if (aggregate.val() != 0 && time.val() != 0) {
            table.clear();
            $.ajax({
                type: "POST",
                url: "/Report/GetAggregateData",
                data: {
                    "time": time.val(),
                    "aggregate": aggregate.val()
                },
                success: function (data) {
                    if (aggregate.val() == 1) {
                        for (var i = 0; i < data.length; i++) {
                            var numStudents = 0;
                            for (var x = 0; x < data[i].courses.length; x++) {
                                numStudents += data[i].courses[x].item1.studentCourses.length;
                            }
                            var name = data[i].name;
                            var conc = data[i].concentrationAvg;
                            console.log(data[i]);
                            console.log(data.length);
                            var text
                            if (data[i].courses.length > 0) {
                                text = "<i class = 'fas fa-plus-square showCourse'></i>"
                            } else {
                                text = "";
                            }
                            var temp = table.row.add([text, name, numStudents, conc.toFixed(2)]).draw();
                            if (data[i].courses.length > 0) {
                                var html = "";
                                html += "<table style = 'width:100%;'><thead> <th style = 'border-bottom: 1px solid #bcbcbc; color: #545454; background-color:#f1f1f1;' >Courses</th><th style = 'border-bottom: 1px solid #bcbcbc; color: #545454; background-color:#f1f1f1;'>Number of Students</th><th style = 'border-bottom: 1px solid #bcbcbc; color: #545454; background-color:#f1f1f1;'>Grade Average</th></thead><tbody>";
                                for (var x = 0; x < data[i].courses.length; x++) {
                                    html += "<tr style = 'color:#5d5d5d; background-color:#f1f1f1;'><td>" + data[i].courses[x].item1.name + "</td><td>" + data[i].courses[x].item1.studentCourses.length + "</td><td>" + data[i].courses[x].item2.toFixed(2) + "</td></tr>";
                                }
                                html += "</tbody ></table >";
                                console.log(html);
                                temp.child(html, 'test');
                            }

                            console.log(temp);
                        }
                        $('#dataTable').removeClass('hidden');

                    } else if (aggregate.val() == 2) {
                        console.log(data);
                        for (var x = 0; x < data[0].courses.length; x++) {
                            var name = data[0].courses[x].item1.name;
                            var avg = data[0].courses[x].item2;
                            if (data[0].courses[x].item1.studentCourses) {
                                var numStudents = data[0].courses[x].item1.studentCourses.length;
                            } else {
                                var numStudents = 0;
                            }
                            text = "";
                            table.row.add([text, name, numStudents, avg.toFixed(2)]).draw();
                            $('#dataTable').removeClass('hidden');
                        }
                    } else if (aggregate.val() == 3) {
                        console.log("hit");
                        console.log(time.val());
                        console.log(time.val());
                        if (time.val() == "Spring 2018") {
                            console.log('hit');
                            table.row.add(['', "The student must be a god at git", "1", "3"]).draw();
                            table.row.add(['', "Test 1", "4", "3.24"]).draw();
                            table.row.add(['', "Test 4", "2", "5"]).draw();
                        } else if (time.val() == "Spring 2019") {
                            table.row.add(['', "The student should be able to program", "0", "0"]).draw();
                        } else if (time.val() == "Summer 2018") {
                            table.row.add(['', "Test 3", "1", "4"]).draw();
                            table.row.add(['', "Test 6", "0", "0"]).draw();
                            table.row.add(['', "Test 5", "0", "0"]).draw();
                        }
                    } else if (aggregate.val() == 4) {
                        if (time.val() == "Spring 2018") {
                            table.row.add(['', "How do you fix a merge conflict?", "2", "2.5"]).draw();
                            table.row.add(['', "How do you commit?", "0", "0"]).draw();
                            table.row.add(['', "This is a question about Git.", "2", "3.5"]).draw();
                        } else if (time.val() == "Spring 2019") {
                            table.row.add(['', "How do you do something in Git?", "0", "0"]).draw();
                            table.row.add(['', "whats a variable", "1", "2"]).draw();
                        } else if (time.val() == "Summer 2018") {
                            table.row.add(['', "Hold this test", "0", "0"]).draw();
                            table.row.add(['', "How do you write hello world?", "0", "0"]).draw();
                            table.row.add(['', "How do you drive a car?", "1", "1"]).draw();
                        }
                    }
                },
                error: function (data) {
                    console.log(data);
                    console.log("Error");
                }
            });
        }
       
    });
</script>