GradExam/Models/Concentration.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace GradExam.Models
{
    public class Concentration
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

	}
}

GradExam/Controllers/ConcentrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GradExam.Models;
using GradExam.Services;
using GradExam.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GradExam.Controllers
{
    [Authorize(Roles ="Admin,Director")]
    public class ConcentrationController : Controller
    {
        private IGradeExamRepository _context;

        public ConcentrationController(IGradeExamRepository context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var concentrations = _context.ReadAllConcentrations();
            return View(concentrations);
        }

        public IActionResult Edit(int id, bool read = false)
        {
            var concentration = _context.ReadConcentration(id);

            var vm = new EditConcentrationViewModel
            {
                ReadOnly = read,
                Id = concentration.Id,
                Title = concentration.Name
            };

            return View(vm);
        }

        [HttpPost]
        public IActionResult Edit(int id, EditConcentrationViewModel vm)
        {
            //Make sure the model state is valid
            if (!ModelState.IsValid)
            {
                return View("Edit", vm);
            }

            Concentration concentration;

            // If we are adding a concentration
            if (id == -1)
            {
                concentration = new Concentration
                {
                    Name = vm.Title
                };

                _context.UpdateConcentration(-1, concentration);
            }
            else //Editing a concentration
            {
                concentration = _context.ReadConcentration(id);

                concentration.Name = vm.Title;

                _context.UpdateConcentration(id, concentration);
            }

            return RedirectToAction("Index");
        }

        public IActionResult Add()
        {
            //Create view model with -1 as id to signify we are adding a concentration
            var vm = new EditConcentrationViewModel();
            vm.Id = -1;

            return View("Edit",vm);
        }

        public IActionResult Delete(int id)
        {
            var con = _context.ReadConcentration(id);
            if (con == null)
            {
                return RedirectToAction("Index");
            }
            return View(con);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            _context.DeleteConcentration(id);
            return RedirectToAction("Index");
        }

		public ActionResult GetList()
		{
			var model = _context.ReadAllConcentrations();
			return Json(new { data = model });
		}
	}
}

GradExam/Views/Concentration/Delete.cshtml
@model GradExam.Models.Concentration

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Concentration</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

GradExam/Views/Concentration/Edit.cshtml
@model GradExam.ViewModels.EditConcentrationViewModel
@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>
@using (Html.BeginForm("Edit", "Concentration"))
{
    <div class="col-sm-4">

        @Html.ValidationSummary()
        <div class="form-group">
            <!--  Needs to be read only  -->
            @Html.LabelFor(model => model.Id)
            @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly"} })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Title)
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
        </div>

        <button type="submit" class="btn btn-primary" id="submit">Submit</button>
    
    </div>
}

<script>
    document.getElementById("Title").readOnly = @(Model.ReadOnly ? "true" : "false");
    $("#submit").css("visibility", "@(Model.ReadOnly ? "hidden" : "")");

</script>

GradExam/Views/Concentration/Index.cshtml
@model IEnumerable<GradExam.Models.Concentration>
@{
	ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
	<a asp-action="Add">Create New</a>
</p>
<table class="display" id="concentrationTable">
		<thead>
			<tr>
				<th>
					@Html.DisplayNameFor(model => model.Id)
				</th>
				<th>
					@Html.DisplayNameFor(model => model.Name)
				</th>
				<th></th>
			</tr>
		</thead>
		@*<tbody>
			@foreach (var item in Model)
			{
				<tr>
					<td>
						@Html.DisplayFor(modelItem => item.Id)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.Name)
					</td>
					<td>
						@Html.ActionLink("Edit", "Edit", "Concentration", new { id = item.Id }) |
						@Html.ActionLink("Details", "Edit", "Concentration", new { id = item.Id, read = true }) |
						@Html.ActionLink("Delete", "Delete", new { id=item.Id  })
					</td>
				</tr>
			}
		</tbody>*@
	</table>
@section Scripts{
	<script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
	<script>
        $(document).ready(function () {

            $("#concentrationTable").DataTable(
                {
                    "ajax": {
                        "url": "/Concentration/GetList",
                        "type": "GET",
                        "dataType": "json"
                    },
                    "columns": [
                        { "data": "id" },
                        { "data": "name" },
                        {
                            mRender: function (data, type, row) {
                                var linkEdit = '@Html.ActionLink("Edit", "Edit", new {id= -1 })';
                                linkEdit = linkEdit.replace("-1", row.id);

                                var linkDetails = '@Html.ActionLink("Details", "Details", new {id= -1 })';
                                linkDetails = linkDetails.replace("-1", row.id);

                                var linkDelete = '@Html.ActionLink("Delete", "Delete", new {id= -1 })';
                                linkDelete = linkDelete.replace("-1", row.id);

                                return linkDetails + " | " + linkEdit + " | " + linkDelete;
                            }
                        }
                    ]
                });
        });

	</script>
	}